set_property PACKAGE_PIN W5 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
create_clock -period 10.000 -name sys_clk_pin -waveform {0.000 5.000} -add [get_ports clk]

set_property PACKAGE_PIN A18 [get_ports Tx]
set_property IOSTANDARD LVCMOS33 [get_ports Tx]
set_property PACKAGE_PIN B18 [get_ports Rx]
set_property IOSTANDARD LVCMOS33 [get_ports Rx]

set_property PACKAGE_PIN W7 [get_ports {C[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {C[0]}]
set_property PACKAGE_PIN W6 [get_ports {C[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {C[1]}]
set_property PACKAGE_PIN U8 [get_ports {C[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {C[2]}]
set_property PACKAGE_PIN V8 [get_ports {C[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {C[3]}]
set_property PACKAGE_PIN U5 [get_ports {C[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {C[4]}]
set_property PACKAGE_PIN V5 [get_ports {C[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {C[5]}]
set_property PACKAGE_PIN U7 [get_ports {C[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {C[6]}]

set_property PACKAGE_PIN U2 [get_ports {AN[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {AN[0]}]
set_property PACKAGE_PIN U4 [get_ports {AN[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {AN[1]}]
set_property PACKAGE_PIN V4 [get_ports {AN[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {AN[2]}]
set_property PACKAGE_PIN W4 [get_ports {AN[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {AN[3]}]

set_property PACKAGE_PIN V17 [get_ports {User_Tx[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {User_Tx[0]}]
set_property PACKAGE_PIN V16 [get_ports {User_Tx[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {User_Tx[1]}]
set_property PACKAGE_PIN W16 [get_ports {User_Tx[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {User_Tx[2]}]
set_property PACKAGE_PIN W17 [get_ports {User_Tx[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {User_Tx[3]}]
set_property PACKAGE_PIN W15 [get_ports {User_Tx[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {User_Tx[4]}]
set_property PACKAGE_PIN V15 [get_ports {User_Tx[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {User_Tx[5]}]
set_property PACKAGE_PIN W14 [get_ports {User_Tx[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {User_Tx[6]}]
set_property PACKAGE_PIN W13 [get_ports {User_Tx[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {User_Tx[7]}]

set_property PACKAGE_PIN U16 [get_ports {User_Tx_LED[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {User_Tx_LED[0]}]
set_property PACKAGE_PIN E19 [get_ports {User_Tx_LED[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {User_Tx_LED[1]}]
set_property PACKAGE_PIN U19 [get_ports {User_Tx_LED[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {User_Tx_LED[2]}]
set_property PACKAGE_PIN V19 [get_ports {User_Tx_LED[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {User_Tx_LED[3]}]
set_property PACKAGE_PIN W18 [get_ports {User_Tx_LED[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {User_Tx_LED[4]}]
set_property PACKAGE_PIN U15 [get_ports {User_Tx_LED[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {User_Tx_LED[5]}]
set_property PACKAGE_PIN U14 [get_ports {User_Tx_LED[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {User_Tx_LED[6]}]
set_property PACKAGE_PIN V14 [get_ports {User_Tx_LED[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {User_Tx_LED[7]}]

set_property PACKAGE_PIN R2 [get_ports Enable_Switch]
set_property IOSTANDARD LVCMOS33 [get_ports Enable_Switch]
set_property PACKAGE_PIN T1 [get_ports Mode]
set_property IOSTANDARD LVCMOS33 [get_ports Mode]

set_property PACKAGE_PIN R3 [get_ports BR_Select[0]]
set_property IOSTANDARD LVCMOS33 [get_ports BR_Select[0]]
set_property PACKAGE_PIN W2 [get_ports BR_Select[1]]
set_property IOSTANDARD LVCMOS33 [get_ports BR_Select[1]]
set_property PACKAGE_PIN U1 [get_ports BR_Select[2]]
set_property IOSTANDARD LVCMOS33 [get_ports BR_Select[2]]