set_property PACKAGE_PIN W5 [get_ports clk]							
	set_property IOSTANDARD LVCMOS33 [get_ports clk]
	create_clock -add -name sys_clk_pin -period 10.00 -waveform {0 5} [get_ports clk]

set_property PACKAGE_PIN A18 [get_ports Tx_Serial]						
	set_property IOSTANDARD LVCMOS33 [get_ports Tx_Serial]
set_property PACKAGE_PIN B18 [get_ports Rx_Serial]						
	set_property IOSTANDARD LVCMOS33 [get_ports Rx_Serial]

set_property PACKAGE_PIN W7 [get_ports C[1]]					
	set_property IOSTANDARD LVCMOS33 [get_ports C[1]]
set_property PACKAGE_PIN W6 [get_ports C[2]]					
	set_property IOSTANDARD LVCMOS33 [get_ports C[2]]
set_property PACKAGE_PIN U8 [get_ports C[3]]					
	set_property IOSTANDARD LVCMOS33 [get_ports C[3]]
set_property PACKAGE_PIN V8 [get_ports C[4]]					
	set_property IOSTANDARD LVCMOS33 [get_ports C[4]]
set_property PACKAGE_PIN U5 [get_ports C[5]]					
	set_property IOSTANDARD LVCMOS33 [get_ports C[5]]
set_property PACKAGE_PIN V5 [get_ports C[6]]					
	set_property IOSTANDARD LVCMOS33 [get_ports C[6]]
set_property PACKAGE_PIN U7 [get_ports C[7]]					
	set_property IOSTANDARD LVCMOS33 [get_ports C[7]]

set_property PACKAGE_PIN U2 [get_ports AN[0]]					
	set_property IOSTANDARD LVCMOS33 [get_ports AN[0]]
set_property PACKAGE_PIN U4 [get_ports AN[1]]					
	set_property IOSTANDARD LVCMOS33 [get_ports AN[1]]
set_property PACKAGE_PIN V4 [get_ports AN[2]]					
	set_property IOSTANDARD LVCMOS33 [get_ports AN[2]]
set_property PACKAGE_PIN W4 [get_ports AN[3]]					
	set_property IOSTANDARD LVCMOS33 [get_ports AN[3]]
	
set_property PACKAGE_PIN V17 [get_ports Tx_Parallel[0]]					
	set_property IOSTANDARD LVCMOS33 [get_ports Tx_Parallel[0]]
set_property PACKAGE_PIN V16 [get_ports Tx_Parallel[1]]					
	set_property IOSTANDARD LVCMOS33 [get_ports Tx_Parallel[1]]
set_property PACKAGE_PIN W16 [get_ports Tx_Parallel[2]]					
	set_property IOSTANDARD LVCMOS33 [get_ports Tx_Parallel[2]]
set_property PACKAGE_PIN W17 [get_ports Tx_Parallel[3]]					
	set_property IOSTANDARD LVCMOS33 [get_ports Tx_Parallel[3]]
set_property PACKAGE_PIN W15 [get_ports Tx_Parallel[4]]					
	set_property IOSTANDARD LVCMOS33 [get_ports Tx_Parallel[4]]
set_property PACKAGE_PIN V15 [get_ports Tx_Parallel[5]]					
	set_property IOSTANDARD LVCMOS33 [get_ports Tx_Parallel[5]]
set_property PACKAGE_PIN W14 [get_ports Tx_Parallel[6]]					
	set_property IOSTANDARD LVCMOS33 [get_ports Tx_Parallel[6]]
set_property PACKAGE_PIN W13 [get_ports Tx_Parallel[7]]					
	set_property IOSTANDARD LVCMOS33 [get_ports Tx_Parallel[7]]	

set_property PACKAGE_PIN U16 [get_ports Parallel_Out[0]]					
	set_property IOSTANDARD LVCMOS33 [get_ports Parallel_Out[0]]
set_property PACKAGE_PIN E19 [get_ports Parallel_Out[1]]					
	set_property IOSTANDARD LVCMOS33 [get_ports Parallel_Out[1]]
set_property PACKAGE_PIN U19 [get_ports Parallel_Out[2]]					
	set_property IOSTANDARD LVCMOS33 [get_ports Parallel_Out[2]]
set_property PACKAGE_PIN V19 [get_ports Parallel_Out[3]]					
	set_property IOSTANDARD LVCMOS33 [get_ports Parallel_Out[3]]
set_property PACKAGE_PIN W18 [get_ports Parallel_Out[4]]					
	set_property IOSTANDARD LVCMOS33 [get_ports Parallel_Out[4]]
set_property PACKAGE_PIN U15 [get_ports Parallel_Out[5]]					
	set_property IOSTANDARD LVCMOS33 [get_ports Parallel_Out[5]]
set_property PACKAGE_PIN U14 [get_ports Parallel_Out[6]]					
	set_property IOSTANDARD LVCMOS33 [get_ports Parallel_Out[6]]
set_property PACKAGE_PIN V14 [get_ports Parallel_Out[7]]					
	set_property IOSTANDARD LVCMOS33 [get_ports Parallel_Out[7]]
	
set_property PACKAGE_PIN R2 [get_ports Enable]					
	set_property IOSTANDARD LVCMOS33 [get_ports Enable]
set_property PACKAGE_PIN T1 [get_ports Mode]					
	set_property IOSTANDARD LVCMOS33 [get_ports Mode]
